name: pymc_env
channels:
  - conda-forge
  - defaults
dependencies:
  - adwaita-icon-theme=48.1=unix_0
  - arviz=0.21.0=pyhd8ed1ab_0
  - atk-1.0=2.38.0=h4bec284_2
  - brotli=1.1.0=h6e16a3a_3
  - brotli-bin=1.1.0=h6e16a3a_3
  - bzip2=1.0.8=hfdf4475_7
  - c-ares=1.34.5=hf13058a_0
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=6.1.0=pyhd8ed1ab_0
  - cairo=1.18.4=h950ec3b_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - cons=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py312hc47a885_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - epoxy=1.5.10=h5eb16cf_1
  - etuples=0.3.9=pyhd8ed1ab_1
  - filelock=3.18.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h37eeddb_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.4=py312h3520af0_0
  - freetype=2.13.3=h694c41f_1
  - fribidi=1.0.10=hbcb3906_0
  - gdk-pixbuf=2.42.12=ha587570_0
  - glib-tools=2.84.2=hf8faeaf_0
  - graphite2=1.3.14=h240833e_0
  - graphviz=13.0.1=hf067352_0
  - gtk3=3.24.43=h70b172e_5
  - gts=0.7.6=h53e17e3_4
  - h5netcdf=1.6.1=pyhd8ed1ab_0
  - h5py=3.12.1=nompi_py312hf5b0cce_103
  - harfbuzz=11.2.1=hdfbcdba_0
  - hdf5=1.14.4=nompi_h1607680_105
  - hicolor-icon-theme=0.17=h694c41f_2
  - icu=75.1=h120a0e1_0
  - kiwisolver=1.4.8=py312h9275861_0
  - krb5=1.21.3=h37d8d59_0
  - lcms2=2.17=h72f5680_0
  - lerc=4.0.0=hcca01a6_1
  - libaec=1.1.4=ha6bc127_0
  - libblas=3.9.0=31_h7f60823_openblas
  - libbrotlicommon=1.1.0=h6e16a3a_3
  - libbrotlidec=1.1.0=h6e16a3a_3
  - libbrotlienc=1.1.0=h6e16a3a_3
  - libcblas=3.9.0=31_hff6cab4_openblas
  - libcurl=8.14.1=h5dec5d8_0
  - libcxx=20.1.7=hf95d169_0
  - libdeflate=1.24=hcc1b750_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libexpat=2.7.0=h240833e_0
  - libffi=3.4.6=h281671d_1
  - libfreetype=2.13.3=h694c41f_1
  - libfreetype6=2.13.3=h40dfd5c_1
  - libgd=2.3.3=h8555400_11
  - libgfortran=15.1.0=h5f6db21_0
  - libgfortran5=15.1.0=hfa3c126_0
  - libglib=2.84.2=h3139dbc_0
  - libiconv=1.18=h4b5e92a_1
  - libintl=0.24.1=h27064b9_0
  - libjpeg-turbo=3.1.0=h6e16a3a_0
  - liblapack=3.9.0=31_h236ab99_openblas
  - liblzma=5.8.1=hd471939_2
  - libnghttp2=1.64.0=hc7306c3_0
  - libopenblas=0.3.29=openmp_hbf64a52_0
  - libpng=1.6.49=h3c4a55f_0
  - librsvg=2.58.4=h21a6cfa_3
  - libsqlite=3.50.1=h7cec44d_6
  - libssh2=1.11.1=hed3591d_0
  - libtiff=4.7.0=h1167cee_5
  - libwebp-base=1.5.0=h6cf52b4_0
  - libxcb=1.17.0=hf1f96e2_0
  - libxml2=2.13.8=h93c44a6_0
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=20.1.7=ha54dae1_0
  - logical-unification=0.4.6=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - matplotlib-base=3.10.3=py312h535dea3_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - minikanren=1.0.3=pyhd8ed1ab_1
  - multipledispatch=0.6.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h0622a9a_3
  - numpy=1.26.4=py312he3a82b2_0
  - openjpeg=2.5.3=h7fd6d84_0
  - openssl=3.5.0=hc426f3f_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.0=py312hec45ffd_0
  - pango=1.56.3=hae8941d_1
  - pcre2=10.45=hf733adb_0
  - pillow=11.2.1=py312hd9f36e3_0
  - pip=25.1.1=pyh8b19718_0
  - pixman=0.46.2=h1fd1274_0
  - pthread-stubs=0.4=h00291cd_1002
  - pygments=2.19.2=pyhd8ed1ab_0
  - pymc=5.23.0=hd8ed1ab_0
  - pymc-base=5.23.0=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pytensor=2.23.0=py312h77d3abe_0
  - pytensor-base=2.31.3=np20py312h17ae09a_0
  - python=3.12.11=h9ccd52b_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-graphviz=0.21=pyhbacfb6d_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=6_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h3c5361c_5
  - readline=8.2=h7cca4af_2
  - rich=14.0.0=pyh29332c3_0
  - scipy=1.15.2=py312hd04560d_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=hf689a15_2
  - toolz=1.0.0=pyhd8ed1ab_1
  - typing_extensions=4.14.0=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py312h01d7ebd_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xarray=2025.6.1=pyhd8ed1ab_1
  - xarray-einstats=0.9.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h6e16a3a_0
  - xorg-libxdmcp=1.1.5=h00291cd_0
  - zstd=1.5.7=h8210216_2
  - pip:
    - absl-py==2.3.1
    - aiosqlite==0.21.0
    - alembic==1.16.2
    - annotated-types==0.7.0
    - anyio==4.9.0
    - appnope==0.1.4
    - apprise==1.9.3
    - asgi-lifespan==2.1.0
    - asttokens==3.0.0
    - asyncpg==0.30.0
    - attrs==25.3.0
    - beautifulsoup4==4.13.4
    - blackjax==1.2.5
    - bs4==0.0.2
    - certifi==2025.6.15
    - cffi==1.17.1
    - charset-normalizer==3.4.2
    - chex==0.1.89
    - click==8.1.8
    - colorama==0.4.6
    - comm==0.2.3
    - coolname==2.2.0
    - cryptography==45.0.4
    - dateparser==1.2.2
    - debugpy==1.8.17
    - decorator==5.2.1
    - docker==7.1.0
    - exceptiongroup==1.3.0
    - executing==2.2.1
    - fastapi==0.115.14
    - fastprogress==1.0.3
    - fsspec==2025.5.1
    - greenlet==3.2.3
    - griffe==1.7.3
    - h11==0.16.0
    - h2==4.2.0
    - hpack==4.1.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - humanize==4.12.3
    - hyperframe==6.1.0
    - idna==3.10
    - importlib-metadata==8.7.0
    - iniconfig==2.1.0
    - ipykernel==6.30.1
    - ipython==9.5.0
    - ipython-pygments-lexers==1.1.1
    - jax==0.4.38
    - jaxlib==0.4.38
    - jaxopt==0.8.5
    - jedi==0.19.2
    - jinja2==3.1.6
    - jinja2-humanize-extension==0.4.0
    - jsonpatch==1.33
    - jsonpointer==3.0.0
    - jsonschema==4.24.0
    - jsonschema-specifications==2025.4.1
    - jupyter-client==8.6.3
    - jupyter-core==5.8.1
    - makefun==1.16.0
    - mako==1.3.10
    - markdown==3.8.2
    - markupsafe==3.0.2
    - matplotlib-inline==0.1.7
    - ml-dtypes==0.5.1
    - nest-asyncio==1.6.0
    - oauthlib==3.3.1
    - opentelemetry-api==1.34.1
    - opt-einsum==3.4.0
    - optax==0.2.5
    - orjson==3.10.18
    - parso==0.8.5
    - pathspec==0.12.1
    - pendulum==3.1.0
    - pexpect==4.9.0
    - platformdirs==4.4.0
    - pluggy==1.6.0
    - prefect==3.4.7
    - prometheus-client==0.22.1
    - prompt-toolkit==3.0.52
    - psutil==7.0.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pycparser==2.22
    - pydantic==2.11.7
    - pydantic-core==2.33.2
    - pydantic-extra-types==2.10.5
    - pydantic-settings==2.10.1
    - pytest==8.4.1
    - python-dotenv==1.1.1
    - python-slugify==8.0.4
    - python-socks==2.7.1
    - pyyaml==6.0.2
    - pyzmq==27.1.0
    - readchar==4.2.1
    - referencing==0.36.2
    - regex==2024.11.6
    - requests==2.32.4
    - requests-oauthlib==2.0.0
    - rfc3339-validator==0.1.4
    - rpds-py==0.26.0
    - ruamel-yaml==0.18.14
    - ruamel-yaml-clib==0.2.12
    - semver==3.0.4
    - shellingham==1.5.4
    - sniffio==1.3.1
    - soupsieve==2.7
    - sqlalchemy==2.0.41
    - stack-data==0.6.3
    - starlette==0.46.2
    - text-unidecode==1.3
    - toml==0.10.2
    - tornado==6.5.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - typer==0.16.0
    - typing-inspection==0.4.1
    - tzlocal==5.3.1
    - ujson==5.10.0
    - urllib3==2.5.0
    - uv==0.7.18
    - uvicorn==0.35.0
    - wcwidth==0.2.13
    - websockets==15.0.1
    - zipp==3.23.0
